name: ml-learning-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - ipython
  - scipy
  - nltk
  - spacy
  - xgboost
  - lightgbm
  - statsmodels
  - pip
  - pip:
      - sentence-transformers
      - openpyxl
